# Generated by Django 6.0.4 on 2026-05-04 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientprofile',
            options={'verbose_name': 'Recruiter Profile', 'verbose_name_plural': 'Recruiter Profiles'},
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='main_field',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='work_types',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='client_type',
            field=models.CharField(choices=[('company', 'Company'), ('individual', 'Individual')], default='individual', max_length=15),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='skills',
            field=models.CharField(blank=True, help_text='Comma-separated tags', max_length=500),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('client', 'Recruiter'), ('admin', 'Administrator')], max_length=10),
        ),
    ]
