# Generated by Django 4.2.29 on 2026-05-15 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_directconversation_directmessage'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='directconversation',
            index=models.Index(fields=['participant1', '-updated_at'], name='conv_p1_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='directconversation',
            index=models.Index(fields=['participant2', '-updated_at'], name='conv_p2_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='directmessage',
            index=models.Index(fields=['conversation', 'is_read'], name='dmessage_conv_read_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['mission', 'is_read'], name='message_mission_read_idx'),
        ),
    ]
