# Generated by Django 4.2.29 on 2026-05-14 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0003_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='application_attachments/'),
        ),
    ]
