# Generated by Django 4.2.29 on 2026-05-14 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0004_add_attachment_to_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='proposed_budget',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='proposed_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
