# Generated by Django 4.2.29 on 2026-05-15 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0005_add_negotiation_to_application'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['student'], name='application_student_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['mission'], name='application_mission_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['status'], name='application_status_idx'),
        ),
        migrations.AddIndex(
            model_name='mission',
            index=models.Index(fields=['status'], name='mission_status_idx'),
        ),
        migrations.AddIndex(
            model_name='mission',
            index=models.Index(fields=['client'], name='mission_client_idx'),
        ),
        migrations.AddIndex(
            model_name='mission',
            index=models.Index(fields=['category'], name='mission_category_idx'),
        ),
        migrations.AddIndex(
            model_name='mission',
            index=models.Index(fields=['status', '-created_at'], name='mission_status_created_idx'),
        ),
    ]
