# Generated by Django 4.2.29 on 2026-05-15 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0002_gig_status'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='gig',
            index=models.Index(fields=['status', 'is_active'], name='gig_status_active_idx'),
        ),
        migrations.AddIndex(
            model_name='gig',
            index=models.Index(fields=['student'], name='gig_student_idx'),
        ),
        migrations.AddIndex(
            model_name='gig',
            index=models.Index(fields=['category'], name='gig_category_idx'),
        ),
    ]
